// Generated by android/configurator/src/shipping.ts. Regenerate; do not edit.
package com.arthack.agentvoice

import androidx.compose.ui.unit.dp

internal data class ShippingLayout(
    val placement: PersonaPlacement,
    val design: PreviewDesign,
    val halo: PreviewHalo,
    val spirit: PreviewSpirit,
    val personaSide: String,
    val horizontalOffsetDp: Int,
)

internal object ShippingDesign {
    const val profileSource = "../../../../../../tmp/agentvoice-wake-clearance/candidate-profile.json"
    const val profileSha256 = "984ef47fbf8d03197e82d1c4cca01e99b845ac93a8b78beebd7c8d6b02740d93"
    const val sessionSha256 = "b9f5a583b4387cda4a9f7e1af6749ce3d3a190bcb08af76882c438b15b391dcc"
    val portrait = ShippingLayout(
        placement = PersonaPlacement(speakingScale = 0.78f, listeningScale = 0.56f, idleScale = 0.78f, offsetY = -37.dp),
        design = PreviewDesign(
            layout = "studio", header = "none",
            controlsHeightDp = 409, controlsWithoutPttDp = 390, holdSharePercent = 36.4,
            traces = PreviewTraces(
                fadeLengthDp = 80,
                footSpacingPercent = 200,
                glowPercent = 67,
                pattern = "splayed",
                personaSpacingPercent = 98,
                reachDp = -9,
                stancePercent = 101,
                tipOpacityPercent = 0,
                weightPercent = 250,
            ),
            spacing = PreviewSpacing(
                channelGapDp = 18,
                edgeClearancePercent = 200,
                paddingDp = 21,
                pushGapDp = 18,
                sectionGapDp = 4,
                sideMarginPercent = 48,
            ),
        ),
        halo = PreviewHalo(
            containedSizePercent = 77,
            idleBreathingPercent = 95,
            idleColor = "#f0f2e9",
            listeningColor = "#d4ff72",
            listeningPulsePercent = 68,
            ringSpreadPercent = 80,
            speakingColor = "#bbaaff",
            speakingMotionPercent = 68,
            variant = "contained",
        ),
        spirit = PreviewSpirit(
            persona = "follow",
            strengthPercent = 51,
            surface = "soft",
        ),
        personaSide = "left", horizontalOffsetDp = 0,
    )
    val landscape = ShippingLayout(
        placement = PersonaPlacement(speakingScale = 0.78f, listeningScale = 0.56f, idleScale = 0.78f, offsetY = 8.dp),
        design = PreviewDesign(
            layout = "studio", header = "none",
            controlsHeightDp = 403, controlsWithoutPttDp = 359, holdSharePercent = 36.4,
            traces = PreviewTraces(
                fadeLengthDp = 80,
                footSpacingPercent = 200,
                glowPercent = 67,
                pattern = "splayed",
                personaSpacingPercent = 98,
                reachDp = -9,
                stancePercent = 101,
                tipOpacityPercent = 0,
                weightPercent = 250,
            ),
            spacing = PreviewSpacing(
                channelGapDp = 18,
                edgeClearancePercent = 200,
                paddingDp = 21,
                pushGapDp = 18,
                sectionGapDp = 4,
                sideMarginPercent = 48,
            ),
        ),
        halo = PreviewHalo(
            containedSizePercent = 81,
            idleBreathingPercent = 95,
            idleColor = "#f0f2e9",
            listeningColor = "#d4ff72",
            listeningPulsePercent = 68,
            ringSpreadPercent = 80,
            speakingColor = "#bbaaff",
            speakingMotionPercent = 68,
            variant = "contained",
        ),
        spirit = PreviewSpirit(
            persona = "follow",
            strengthPercent = 51,
            surface = "soft",
        ),
        personaSide = "left", horizontalOffsetDp = -38,
    )
    val portraitReverse = ShippingLayout(
        placement = PersonaPlacement(speakingScale = 0.78f, listeningScale = 0.56f, idleScale = 0.78f, offsetY = -22.dp),
        design = PreviewDesign(
            layout = "studio", header = "none",
            controlsHeightDp = 415, controlsWithoutPttDp = 390, holdSharePercent = 36.4,
            traces = PreviewTraces(
                fadeLengthDp = 80,
                footSpacingPercent = 200,
                glowPercent = 67,
                pattern = "splayed",
                personaSpacingPercent = 98,
                reachDp = -9,
                stancePercent = 101,
                tipOpacityPercent = 0,
                weightPercent = 250,
            ),
            spacing = PreviewSpacing(
                channelGapDp = 18,
                edgeClearancePercent = 200,
                paddingDp = 21,
                pushGapDp = 18,
                sectionGapDp = 4,
                sideMarginPercent = 48,
            ),
        ),
        halo = PreviewHalo(
            containedSizePercent = 77,
            idleBreathingPercent = 95,
            idleColor = "#f0f2e9",
            listeningColor = "#d4ff72",
            listeningPulsePercent = 68,
            ringSpreadPercent = 80,
            speakingColor = "#bbaaff",
            speakingMotionPercent = 68,
            variant = "contained",
        ),
        spirit = PreviewSpirit(
            persona = "follow",
            strengthPercent = 51,
            surface = "soft",
        ),
        personaSide = "left", horizontalOffsetDp = 0,
    )
    val landscapeReverse = ShippingLayout(
        placement = PersonaPlacement(speakingScale = 0.78f, listeningScale = 0.56f, idleScale = 0.78f, offsetY = 8.dp),
        design = PreviewDesign(
            layout = "studio", header = "none",
            controlsHeightDp = 421, controlsWithoutPttDp = 359, holdSharePercent = 36.4,
            traces = PreviewTraces(
                fadeLengthDp = 80,
                footSpacingPercent = 200,
                glowPercent = 67,
                pattern = "splayed",
                personaSpacingPercent = 98,
                reachDp = -9,
                stancePercent = 101,
                tipOpacityPercent = 0,
                weightPercent = 250,
            ),
            spacing = PreviewSpacing(
                channelGapDp = 18,
                edgeClearancePercent = 200,
                paddingDp = 21,
                pushGapDp = 18,
                sectionGapDp = 4,
                sideMarginPercent = 48,
            ),
        ),
        halo = PreviewHalo(
            containedSizePercent = 81,
            idleBreathingPercent = 95,
            idleColor = "#f0f2e9",
            listeningColor = "#d4ff72",
            listeningPulsePercent = 68,
            ringSpreadPercent = 80,
            speakingColor = "#bbaaff",
            speakingMotionPercent = 68,
            variant = "contained",
        ),
        spirit = PreviewSpirit(
            persona = "follow",
            strengthPercent = 51,
            surface = "soft",
        ),
        personaSide = "left", horizontalOffsetDp = -36,
    )
    val sounds = PreviewSounds(
        family = "rocker-13",
        volumePercent = 60,
    )
    val icons = PreviewIcons(
        channels = "noun-icons",
        push = "current",
    )
    const val launcher = "relay-aperture"
    const val theme = "bright"
    const val mutedPresence = "tide"
    const val presenceScope = "any-muted"
    val mutedTuning = PreviewMutedTuning(
        breathPercent = 100,
        brightnessPercent = -19,
        cycleSeconds = 13,
        driftPercent = 196,
        motion = "ripple",
        textSizeSp = 32,
    )
    const val showPushToTalk = true
}
