// Generated by android/configurator/src/shipping.ts. Regenerate; do not edit.
package com.arthack.agentvoice

import androidx.compose.ui.unit.dp

internal data class ShippingLayout(
    val placement: PersonaPlacement,
    val design: PreviewDesign,
    val halo: PreviewHalo,
    val spirit: PreviewSpirit,
    val personaSide: String,
    val horizontalOffsetDp: Int,
)

internal object ShippingDesign {
    const val profileSource = "../../../../../../Volumes/Scratch/agentvoice-layout-study-20260911/candidate-profile.json"
    const val profileSha256 = "0e5554a7f1bb36740dcfefc7af3075a3f21cc7e7bdbe575490811ca0c3fedc87"
    const val sessionSha256 = "4d2c6cbb1f1a336b6ff890bc23e9ebab380ac4e8ac3727a9e7ca1af9a5ea38fe"
    val portrait = ShippingLayout(
        placement = PersonaPlacement(speakingScale = 0.78f, listeningScale = 0.56f, idleScale = 0.78f, offsetY = -35.dp),
        design = PreviewDesign(
            layout = "studio", header = "none",
            controlsHeightDp = 407, controlsWithoutPttDp = 388, holdSharePercent = 36.4,
            traces = PreviewTraces(
                fadeLengthDp = 80,
                footSpacingPercent = 200,
                glowPercent = 67,
                pattern = "splayed",
                personaSpacingPercent = 98,
                reachDp = -9,
                stancePercent = 101,
                tipOpacityPercent = 0,
                weightPercent = 250,
            ),
            spacing = PreviewSpacing(
                channelGapDp = 18,
                edgeClearancePercent = 200,
                paddingDp = 21,
                pushGapDp = 18,
                sectionGapDp = 4,
                sideMarginPercent = 48,
            ),
        ),
        halo = PreviewHalo(
            containedSizePercent = 77,
            idleBreathingPercent = 95,
            idleColor = "#f0f2e9",
            listeningColor = "#d4ff72",
            listeningPulsePercent = 68,
            ringSpreadPercent = 80,
            speakingColor = "#bbaaff",
            speakingMotionPercent = 68,
            thinkingWingspan = 5,
            variant = "contained",
        ),
        spirit = PreviewSpirit(
            persona = "follow",
            strengthPercent = 51,
            surface = "soft",
        ),
        personaSide = "left", horizontalOffsetDp = 0,
    )
    val landscape = ShippingLayout(
        placement = PersonaPlacement(speakingScale = 0.78f, listeningScale = 0.56f, idleScale = 0.78f, offsetY = 8.dp),
        design = PreviewDesign(
            layout = "studio", header = "none",
            controlsHeightDp = 401, controlsWithoutPttDp = 357, holdSharePercent = 36.4,
            traces = PreviewTraces(
                fadeLengthDp = 80,
                footSpacingPercent = 200,
                glowPercent = 67,
                pattern = "splayed",
                personaSpacingPercent = 98,
                reachDp = -9,
                stancePercent = 101,
                tipOpacityPercent = 0,
                weightPercent = 250,
            ),
            spacing = PreviewSpacing(
                channelGapDp = 18,
                edgeClearancePercent = 200,
                paddingDp = 21,
                pushGapDp = 18,
                sectionGapDp = 4,
                sideMarginPercent = 48,
            ),
        ),
        halo = PreviewHalo(
            containedSizePercent = 81,
            idleBreathingPercent = 95,
            idleColor = "#f0f2e9",
            listeningColor = "#d4ff72",
            listeningPulsePercent = 68,
            ringSpreadPercent = 80,
            speakingColor = "#bbaaff",
            speakingMotionPercent = 68,
            thinkingWingspan = 5,
            variant = "contained",
        ),
        spirit = PreviewSpirit(
            persona = "follow",
            strengthPercent = 51,
            surface = "soft",
        ),
        personaSide = "left", horizontalOffsetDp = -43,
    )
    val portraitReverse = ShippingLayout(
        placement = PersonaPlacement(speakingScale = 0.78f, listeningScale = 0.56f, idleScale = 0.78f, offsetY = -20.dp),
        design = PreviewDesign(
            layout = "studio", header = "none",
            controlsHeightDp = 413, controlsWithoutPttDp = 388, holdSharePercent = 36.4,
            traces = PreviewTraces(
                fadeLengthDp = 80,
                footSpacingPercent = 200,
                glowPercent = 67,
                pattern = "splayed",
                personaSpacingPercent = 98,
                reachDp = -9,
                stancePercent = 101,
                tipOpacityPercent = 0,
                weightPercent = 250,
            ),
            spacing = PreviewSpacing(
                channelGapDp = 18,
                edgeClearancePercent = 200,
                paddingDp = 21,
                pushGapDp = 18,
                sectionGapDp = 4,
                sideMarginPercent = 48,
            ),
        ),
        halo = PreviewHalo(
            containedSizePercent = 77,
            idleBreathingPercent = 95,
            idleColor = "#f0f2e9",
            listeningColor = "#d4ff72",
            listeningPulsePercent = 68,
            ringSpreadPercent = 80,
            speakingColor = "#bbaaff",
            speakingMotionPercent = 68,
            thinkingWingspan = 5,
            variant = "contained",
        ),
        spirit = PreviewSpirit(
            persona = "follow",
            strengthPercent = 51,
            surface = "soft",
        ),
        personaSide = "left", horizontalOffsetDp = 0,
    )
    val landscapeReverse = ShippingLayout(
        placement = PersonaPlacement(speakingScale = 0.78f, listeningScale = 0.56f, idleScale = 0.78f, offsetY = 8.dp),
        design = PreviewDesign(
            layout = "studio", header = "none",
            controlsHeightDp = 419, controlsWithoutPttDp = 357, holdSharePercent = 36.4,
            traces = PreviewTraces(
                fadeLengthDp = 80,
                footSpacingPercent = 200,
                glowPercent = 67,
                pattern = "splayed",
                personaSpacingPercent = 98,
                reachDp = -9,
                stancePercent = 101,
                tipOpacityPercent = 0,
                weightPercent = 250,
            ),
            spacing = PreviewSpacing(
                channelGapDp = 18,
                edgeClearancePercent = 200,
                paddingDp = 21,
                pushGapDp = 18,
                sectionGapDp = 4,
                sideMarginPercent = 48,
            ),
        ),
        halo = PreviewHalo(
            containedSizePercent = 81,
            idleBreathingPercent = 95,
            idleColor = "#f0f2e9",
            listeningColor = "#d4ff72",
            listeningPulsePercent = 68,
            ringSpreadPercent = 80,
            speakingColor = "#bbaaff",
            speakingMotionPercent = 68,
            thinkingWingspan = 5,
            variant = "contained",
        ),
        spirit = PreviewSpirit(
            persona = "follow",
            strengthPercent = 51,
            surface = "soft",
        ),
        personaSide = "left", horizontalOffsetDp = -34,
    )
    val sounds = PreviewSounds(
        family = "rocker-13",
        volumePercent = 60,
    )
    val icons = PreviewIcons(
        channels = "noun-icons",
        push = "current",
    )
    const val launcher = "relay-aperture"
    const val connectionStyle = "relay"
    const val theme = "bright"
    const val mutedPresence = "tide"
    const val presenceScope = "any-muted"
    val mutedTuning = PreviewMutedTuning(
        breathPercent = 100,
        brightnessPercent = -19,
        cycleSeconds = 13,
        driftPercent = 196,
        motion = "ripple",
        textSizeSp = 32,
    )
    const val showPushToTalk = true
}
